### ISSUE TITLE
Any chance we could allow passing in flags for the headless_shell process somehow?

### ISSUE THREAD

**Issue by elsigh** [yukinying/chrome-headless-travis-build#1]
I want to tinker with `--no-scrollbars` `--deterministic-fetch` and others.. I don't know if one can pass flags somehow via the docker command given the Dockerfile's hardcoded flags today.

**Comment by yukinying** [comment]
You can just run your docker container with those flags after the image name, as long as the flags are not in conflict with the hardcoded flags. E.g.
```
docker run -i -t --rm --name=chrome-headless -p=127.0.0.1:9222:9222 \
  yukinying/chrome-headless  --no-scrollbars --deterministic-fetch
```

Otherwise, you can use `--entrypoint` option to override the default and then provide the flags after the image name. E.g. 
```
docker run -i -t --rm --name=chrome-headless -p=127.0.0.1:9222:9222 \
  --entrypoint=/chrome/headless yukinying/chrome-headless  \
  --no-scrollbars --deterministic-fetch
```

Please let me know if that does not work.

**Comment by elsigh** [comment]
Cool, thanks you will try that today =)

**Comment by elsigh** [comment]
I tried the first approach, but my screenshot still showed scrollbars.
Trying the second I get the following:
```
elsigh@Lindseys-MacBook-Pro-2:~/src/shift/dpxdt (headless-chrome) $ docker run -i -t --shm-size=256m --rm --name=chrome-headless -p=127.0.0.1:9222:9222 --entrypoint=/chrome/headless yukinying/chrome-headless --deterministic-fetch --no-scrollbars
docker: Error response from daemon: oci runtime error: container_linux.go:247: starting container process caused "exec: \"/chrome/headless\": stat /chrome/headless: no such file or directory"
```

Also, note that even with docker 1.13 I still need the `shm-size` flag or else my process crashes sometimes.

Thanks Albert =)

**Comment by yukinying** [comment]
Sorry I have provided the wrong entrypoint. It should be `--entrypoint /chrome/headless_shell`. You would also need to provide the hardcoded flag again to make devtool works if you use port 9222 for getting the screenshot. See https://github.com/yukinying/chrome-headless-travis-build/blob/master/Dockerfile for the hardcoded flags.

Lastly, the flag to be used should be --hide-scrollbars (and some other customizable flags), according to https://chromium.googlesource.com/chromium/src.git/+/master/headless/app/headless_shell_switches.cc

I bet this would work for taking screenshot:
```
docker run -i -t --shm-size=1024m --rm --name=chrome-headless -p=127.0.0.1:9222:9222 \
  -v $(pwd)/screenshot:/screenshot -w /screenshot \
  --entrypoint=/chrome/headless_shell yukinying/chrome-headless  \
  --no-sandbox \
  --screenshot --hide-scrollbars --deterministic-fetch --virtual-time-budget=5000 \
  https://www.yahoo.com 
```
