### ISSUE TITLE
How to use with Selenium for headless browsing?

### ISSUE THREAD

**Issue by vgoklani** [yukinying/chrome-headless-travis-build#3]
How do we use this with Selenium for headless browsing? I tried this via ipython:

	from selenium import webdriver
	from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

	driver = webdriver.Remote(command_executor='http://localhost:9222/', desired_capabilities=DesiredCapabilities.CHROME)

but received this error:

    WebDriverException: Message:

**Comment by yukinying** [comment]
I am not an expert on Selenium. If I remember correctly, command_executor expects a selenium hub url (in wd/hub format), and which in turns create browser instances. 

Also, there seems to be some related discussion in the official discussion group: https://groups.google.com/a/chromium.org/forum/#!searchin/headless-dev/selenium/headless-dev/VytKt327v2I/PlmBNG5KBAAJ .
