### ISSUE TITLE
Connecting chrome to headless_shell on 9222

### ISSUE THREAD

**Issue by ilanc** [yukinying/chrome-headless-travis-build#5]
Hi Albert,
Wow! thanks for this and chrome-headless-browser-docker. This is more a question than an issue:
1. Have you had any luck connecting chrome to headless_shell? to see what's going on in the headless tab.
2. Have you integrated selenium/chromedriver with headless_shell (or know whether this is possible?) 

I've successfully run `chrome-headless-browser-docker` and connected to it on http://localhost:9222/ using chrome running in the host. This works in both windows and ubuntu hosts. 

I have not managed to connect using `chrome-headless` however. I can get as far as the start page i.e. `Inspectable WebContents`  but when I click on the link to try see whats going on in a headless tab I get a 404, whereas with `chrome-headless-browser-docker` I see the page as expected.

**Comment by ilanc** [comment]
I also tried copying the `/chrome/` directory from within the docker image out into the host operating system (ubuntu in my case - I know headless_shell is compiled under debian) and ran `./headless_shell --no-sandbox --remote-debugging-port=9222 --disable-gpu`. I get the same behavior - i.e. start page works, 404 when connecting to the tab page.

**Comment by ilanc** [comment]
On the plus side selenium and chromedriver 2.30 seem to work fine with `headless_shell`

**Comment by yukinying** [comment]
I know the answer, but I haven't verified if it is still the case.
> 1. Have you had any luck connecting chrome to headless_shell? to see what's going on in the headless tab.

Yes. I started the project with headless shell before headless chrome. At that time, connecting to headless shell with chrome just work like a charm.

> 2. Have you integrated selenium/chromedriver with headless_shell (or know whether this is possible?)

Selenium and chromedriver are both based on chrome devtools protocol. It should work as the above.

**Comment by yukinying** [comment]
It looks like chrome has changed the way to open the remote debug interface. The following is a screenshot of the new interface. I should update the README.
 
<img width="754" alt="screen shot 2017-07-13 at 9 03 57 pm" src="https://user-images.githubusercontent.com/1326727/28197918-e35585d2-680e-11e7-80d1-cceaf05b3c0f.png">

**Comment by ilanc** [comment]
Magic! that works perfectly, thanks
